#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in4,    gyro,           sensorNone)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  leftTouch,      sensorTouch)
#pragma config(Sensor, dgtl7,  rightTouch,     sensorTouch)
#pragma config(Sensor, dgtl8,  sonarSensor,    sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, PIDControl, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex269_MC29, PIDControl, reversed, driveLeft, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/****************************************************
Name: Sargun Singh
Period: 5
Date: 5/11/20
Assignment: Roboslalom III - 3 Sensors
Program Description: Follow the black line until the end.
Algorithm:
1. Go straight
2. Go right
3. Go left
4. Go right
5. Go left
6. Go straight
7. Stop bot
************************************************************************/
//Variables
int threshold = 840; //the average of the values read by the sensors when the bot is over light and dark is 712.
bool leftNotLight ; //one boolean variable is set for the left sensor.
bool centerNotLight ; //one boolean variable is set for the center sensor.
bool rightNotLight ; //one boolean variable is set for the right sensor.
//Functions
void goStraight(); //tells the bot to move forward.
void goRight(); //tells bot to turn right.
void goLeft(); //tells bot to turn left.
void slightLeft(); //tells bot to shift left.
void slightRight(); //tells bot to shift right.
//----------------------------------------------------------------------
task main()
{
while (true)
{
goStraight(); //tells the bot to move forward.
slightRight();
goRight();
slightLeft();
goLeft(); //tells bot to turn left.
goRight();
goLeft(); //tells bot to turn left.
goStraight(); //tells the bot to move forward.
}
}

//Function Glossary **************************************************************************************
void goStraight() //tells bot to go straight.
  {
  	rightNotLight = SensorValue[rightLineFollower]>threshold; //it is true when the function when the right sensor reads a value greater than the threshold.
  	leftNotLight = SensorValue[leftLineFollower]>threshold; //it is true when the left sensor reads a value greater than the threshold.
    centerNotLight = SensorValue[centerLineFollower]>threshold; //it is true when the function when the center sensor reads a value greater than the threshold.
if (!leftNotLight && centerNotLight && !rightNotLight) //if the left sensor sees dark and the center sensor sees dark, perform the function.
		motor[rightMotor] = 63; //sets the right motor to half power, 63.
    motor[leftMotor] = 63; //sets the left motor to half power, 63.
  }

void slightRight() //tells bot to shift right.
  {
  	rightNotLight = SensorValue[rightLineFollower]>threshold; //it is true when the function when the right sensor reads a value greater than the threshold.
  	leftNotLight = SensorValue[leftLineFollower]>threshold; //it is true when the left sensor reads a value greater than the threshold.
    centerNotLight = SensorValue[centerLineFollower]>threshold; //it is true when the function when the center sensor reads a value greater than the threshold.
if (!leftNotLight && centerNotLight && rightNotLight) //if the left sensor sees dark and the center sensor sees dark, perform the function.
		motor[rightMotor] = 30; //sets the right motor to half power, 32.
    motor[leftMotor] = 50; //sets the left motor to half power, 63.
  }

void goRight() //tells bot to go right.
  {
  	rightNotLight = SensorValue[rightLineFollower]>threshold; //it is true when the right sensor reads a value greater than the threshold.
  	leftNotLight = SensorValue[leftLineFollower]>threshold; //it is true when the left sensor reads a value greater than the threshold.
    centerNotLight = SensorValue[centerLineFollower]>threshold; //it is true when perform the function when the center sensor reads a value greater than the threshold.
if (!leftNotLight && !centerNotLight && rightNotLight) //if the left sensor sees light and the center sensor sees dark, perform the function.
  	motor[rightMotor] = 0; //sets the right motor to the power level 12.
    motor[leftMotor] = 63; //sets the left motor to half power, 63.
  }

void slightLeft() //tells bot to shift left.
  {
  	rightNotLight = SensorValue[rightLineFollower]>threshold; //it is true when the right sensor reads a value greater than the threshold.
  	leftNotLight = SensorValue[leftLineFollower]>threshold; //it is true when the left sensor reads a value greater than the threshold.
    centerNotLight = SensorValue[centerLineFollower]>threshold; //it is true when the center sensor reads a value greater than the threshold.
if (leftNotLight && centerNotLight && !rightNotLight) //if the left sensor sees dark and the center sensor sees light, perform the function.
  	motor[rightMotor] = 50; //sets the right motor to half power, 63.
    motor[leftMotor] = 30; //sets the left motor to the power level 32.
  }

void goLeft() //tells bot to go left.
  {
  	rightNotLight = SensorValue[rightLineFollower]>threshold; //it is true when the right sensor reads a value greater than the threshold.
  	leftNotLight = SensorValue[leftLineFollower]>threshold; //it is true when the left sensor reads a value greater than the threshold.
    centerNotLight = SensorValue[centerLineFollower]>threshold; //it is true when the center sensor reads a value greater than the threshold.
if (leftNotLight && !centerNotLight && !rightNotLight) //if the left sensor sees dark and the center sensor sees light, perform the function.
  	motor[rightMotor] = 100; //sets the right motor to half power, 63.
    motor[leftMotor] = 0; //sets the left motor to the power level 12.
  }
