#pragma config(StandardModel, "RVW Anemobot")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/****************************************************
Name: Sargun Singh
Period: 5
Date: 5/28/20
Assignment: Ruins of Atlantis
Program Description: Robot travels through ruins and collects treasure.
Algorithm:
1. go back
2. go forward
3. turn right
4. go forward
5. go back
6. turn left
7. go forward
8. turn left
9. go forward
10. turn right
11. go forward
12. turn right
13. go forward
14. turn left
15. go forward
16. go back
17. go right
18. go forward
19. go back
20. go forward
21. turn right
22. go forward
23. go back
24. turn left
25. go forward
26. turn left
27. go forward
28. turn right
29. go forward
30. turn right
31. go forward
32. turn left
33. go forward
34. go back
35. go right
36. go forward
37. stop bot
************************************************************************/
//Variables
int degreesForRight = 750; //
int backDistance = -450;
int degreesForLeft = 70;
int fwdDistance = 1000;
//Functions
void goBack(int backDistance = -450);
void rightEncoderFwd();
void rightTurn(int degreesForRight = 750);
void goForward();
void leftTurn(int degreesForLeft = 100);
void leftEncoderFwd (int fwdDistance = 1050);
//----------------------------------------------------------------------

task main()
{
goBack(backDistance); //
rightEncoderFwd(); //
rightTurn(); //
goForward(); //
goBack(backDistance = 500); //
leftTurn(degreesForLeft); //
leftEncoderFwd(fwdDistance); //
leftTurn(degreesForLeft = -800);//
leftEncoderFwd (fwdDistance = 2300); //
rightTurn(degreesForRight = 15); //
leftEncoderFwd(fwdDistance = 2800); //
rightTurn(degreesForRight = 270); //
leftEncoderFwd(fwdDistance = 4420); //
SensorValue [gyro] = 0; //
leftTurn(degreesForLeft = -500); //
leftEncoderFwd(fwdDistance = 4940); //
goBack(backDistance = 4480); //
rightTurn(degreesForRight = 600); //
leftEncoderFwd(fwdDistance = 5400); //
SensorValue [gyro] = 0; //
rightTurn(degreesForRight = 1800);
leftEncoderFwd(fwdDistance = 5700);
leftTurn(degreesForLeft = 220);
leftEncoderFwd(fwdDistance = 6650);
rightTurn(degreesForRight = 825);
leftEncoderFwd(fwdDistance = 8280);
rightTurn(degreesForRight = 1700);
leftEncoderFwd(fwdDistance = 9250);
rightTurn(degreesForRight = 1900);
leftEncoderFwd(fwdDistance = 10150);
rightTurn(degreesForRight = 2300);
leftEncoderFwd(fwdDistance = 10405);
goBack(backDistance = 10150);
leftTurn(degreesForLeft = 1160);
leftEncoderFwd(fwdDistance = 10250);
leftTurn(degreesForLeft = 900);
leftEncoderFwd(fwdDistance = 10800);
leftTurn(degreesForLeft = 150);
leftEncoderFwd(fwdDistance = 11300);
goBack(backDistance = 10700);
rightTurn(degreesForRight = 900);
leftEncoderFwd(fwdDistance = 11580);
leftTurn(degreesForLeft = 60);
leftEncoderFwd(fwdDistance = 13560);
SensorValue [gyro] = 0;
leftTurn(degreesForLeft = -900);
leftEncoderFwd(fwdDistance = 14320);
goBack(backDistance = 13360);
rightTurn(degreesForRight = -40);
leftEncoderFwd(fwdDistance = 14920);
SensorValue [gyro] = 0;
rightTurn(degreesForRight = 900);
leftEncoderFwd(fwdDistance = 16310);
leftTurn(degreesForLeft = -30);
leftEncoderFwd(fwdDistance = 17000);
goBack(backDistance = 16040);
rightTurn(degreesForRight = -450);
leftEncoderFwd(fwdDistance = 20000);
}
// Function Glossary############################################################

void goBack(int backDistance)
{
while (SensorValue [rightEncoder] > backDistance)
{
	motor[rightMotor] = -50;
	motor[leftMotor] = -50;
}
}

void rightEncoderFwd()
{
while (SensorValue [rightEncoder] <= 544)
{
	motor[rightMotor] = 50;
	motor[leftMotor] = 50;
}
}

void rightTurn(int degreesForRight)
{
while (SensorValue [gyro] < degreesForRight)
{
	motor[rightMotor] = -50;
	motor[leftMotor] = 50;
}
}

void goForward()
{
while (SensorValue [lightSensor] < 2300)
{
	motor[rightMotor] = 50;
	motor[leftMotor] = 50;
}
}

void leftTurn(int degreesForLeft)
{
while (SensorValue [gyro] > degreesForLeft)
{
	motor[rightMotor] = 50;
	motor[leftMotor] = -50;
}
}

void leftEncoderFwd(int fwdDistance)
{
while (SensorValue [leftEncoder] < fwdDistance)
{
  motor[rightMotor] = 50;
	motor[leftMotor] = 50;
}
}
